<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXYXMwdb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXYXMwdb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXYXMwdb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXYXMwdb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXYXMwdb\App_KernelDevDebugContainer([
    'container.build_hash' => 'XYXMwdb',
    'container.build_id' => 'e47a201b',
    'container.build_time' => 1702893236,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXYXMwdb');
